name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release /p:ContinuousIntegrationBuild=true --no-restore

    - name: Pack
      run: dotnet pack "src/JNet.Runtime" -c Release --no-build

    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: src/JNet.Runtime/bin/Release/*.nupkg