name: JNet pack

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true

jobs:
  pack:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Pack
      run: dotnet pack "src/JNet"
        -c Release
        -o .ci/artifacts
        -p:PackageVersion=${{ github.event.inputs.package_version }}

    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: .ci/artifacts/*.nupkg
